schema_version = "1.0.0"

id = "cloudcreator"
version = "1.0.0"
name = "CloudCreator"
tagline = "CloudCreator by plainprince"
maintainer = "plainprince"
type = "add-on"

tags = ["Render"]

blender_version_min = "4.3.0"

license = ["SPDX:GPL-3.0-or-later"]
